class ErrorCode:
    """Constants for error codes"""

    MAX_ALLOWED_WORDS = "MAX_ALLOWED_WORDS"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    INVALID_TOKEN = "INVALID_TOKEN"
    DUPLICATE_EMAIL = "DUPLICATE_EMAIL"
    PASSWORD_MISMATCH = "PASSWORD_MISMATCH"
    USER_NOT_FOUND = "USER_NOT_FOUND"
